version: "3.8"

services:
  backend:
    image: joanchege/backendyolo-image:latest  # Assuming backend image exists
    ports:
     - "5000:5000"
     
  client:
    image: joanchege/clientyolo-image:latest  # Use the pre-built image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
