version: "3.8"

services:
  backend:
    #build: ./backend  # Path to the backend Dockerfile directory
    image: joanchege/backend-image:v1.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  client:
    #build: ./client  # Path to the client Dockerfile directory
    image: joanchege/client-image:v3.0.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
     - ./client:/app
