version: "3.8"

services:
  backend:
    build: ./backend #path to the backend dockerfile
    ports:
      - "5000:5000"


  frontend:
    build: ./client #path to the client dockerfile
    ports:
     - "3000:3000"
    environment:
      - NODE_ENV=development
