version: "3.8"

services:
  backend:
    build: ./backend  # Path to the backend Dockerfile directory
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  client:
    build: ./client  # Path to the client Dockerfile directory
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
