- hosts: vagrant
  become: true
  var_files:
    - vars/playbook.yml

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

  roles:
   - role: client
   - role: backend

  tasks:
  - name: Clone code form Github
    git: 
      repo: https://github.com/JoanChege/yolo.git


 