---
- hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes


  tasks:
  - name: Clone code from GitHub
    git: 
      repo: https://github.com/JoanChege/yolo.git
      dest: /home/joanchege/dev/code/IP2/yolo/yolo_clone

  - name: Start Docker Service
    become: yes
    service: 
      name: docker
      state: started

  - name: Build Client Docker image
    docker_image:
        name: client
        source: build
        build: 
          path: /home/joanchege/dev/code/IP2/yolo/yolo_clone/client
        state: present
    tags:
      - client

  - name: Run client container
    docker_container:
      name: client
      image: client
      ports:
        - "3000:3000"
      env:
        NODE_ENV: production
      restart_policy: unless-stopped
    tags:
      - client

  - name: Build Backend Docker image
    docker_image:
        name: backend
        source: build
        build: 
          path: /home/joanchege/dev/code/IP2/yolo/yolo_clone/backend
        state: present
    tags:
      - backend

  - name: Run backend container
    docker_container:
      name: backend
      image: backend
      ports:
        - "5000:5000"
      env:
        NODE_ENV: production
      restart_policy: unless-stopped
    tags:
      - backend
