---
- hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

  roles:
  - role: client
  - role: backend

  tasks:
  - name: Clone code from GitHub
    git: 
      repo: https://github.com/JoanChege/yolo.git
      dest: /home/joanchege/dev/code/IP2/yolo/clone

